import requests
import csv

url = "http://localhost:19002/query/service"

headers = {
    "Content-Type": "application/x-www-form-urlencoded"
}


csv_filename = "query_metrics.csv"

# Define data for the query
data = {
"statement": "DROP DATAVERSE wiscon IF EXISTS;CREATE DATAVERSE wiscon;USE wiscon; CREATE TYPE OpenType AS {uid: uuid }; CREATE DATASET wiscondef (OpenType) PRIMARY KEY uid AUTOGENERATED;LOAD DATASET wiscondef USING localfs (('path' = 'localhost:///home/dbis-nuc10/DBIS/data/wiscon103.adm'),  ('format' = 'adm'));",
    "pretty": "true",
    "client_context_id": "xyz"
}

response = requests.post(url, headers=headers, data=data)
print(response.text)